name: Update PDF file

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex

      - name: Check pdf file
        run: |
          file main.pdf | grep -q ' PDF '

      - name: Commit and Push PDF
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "${{ secrets.USER }}"
          git config --global user.email "${{ secrets.EMAIL }}"
          git add main.pdf
          git commit -m "updated pdf file"
          git push
